version: '3'
services:
  container1:
    build:
      context: ./container1
    ports:
      - "7800:7800"
    volumes:
      - ./container1/static:/app/static
    networks:
      - my_network

  container2:
    build:
      context: ./container2
    networks:
      - my_network

networks:
  my_network:
    driver: bridge