version: '3'
services:
  container1:
    image: container1
    ports:
      - "7800:7800"
    volumes:
      - ./container1/static:/app/static
    networks:
      - my_network

  container2:
    image: container2
    networks:
      - my_network
    depends_on:
      - container1

networks:
  my_network:
    driver: bridge